variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_DEPTH: 1

stages:
- preparing
- deploy

generate_datasets:
  image: registry.gitlab.rlp.net/adwmainz/nfdi4culture/cdmd/static-publishing-backend/static-publishing-backend:latest
  stage: preparing
  script:
  - ./modules/datasets-generator/datasets-generator.sh
  artifacts:
    paths:
    - public

pages:
  image: alpine:latest
  stage: deploy
  script:
  - echo "deploy"
  artifacts:
    paths:
    - public
  only:
  - master
  - main

# sudo gitlab-ci-local && sudo chown -R claudius:claudius .